server:
  port:8080

spring:
  datasource:
    url:
      jdbc:mysql://localhost:3306/one-service?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username:
      root
    password:
      Qaz515388
    driver-class-name:
      com.mysql.cj.jdbc.Driver

mybatis:
    mapper-locations:
      classpath:/mapper/**/*.xml